project:
  type: website
  render:
    - "*.qmd"
    - "posts/*.qmd"
    - "!study/**"

website:
  title: "Occasional Divergences"
  site-url: "https://www.occasionaldivergences.com"
  repo-url: "https://github.com/marcdotson/occasional-divergences"
  description: "Two brothers with a mostly Bayesian focus."
  favicon: favicon.png
  twitter-card: true
  open-graph: true
  navbar:
    foreground: "#fff"
    pinned: true
    left:
      - text: "Two brothers with a mostly Bayesian focus."
        file: about.qmd
    right:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "{{< fa brands github size=large >}}"
        url: https://github.com/marcdotson
      - text: "{{< fa brands bluesky size=large >}}"
        url: https://bsky.app/profile/marcdotson.com
  page-footer:
    left:
      - href: https://www.quarto.org
        text: Built with Quarto
    right:
      - text: "&copy; License"
        file: license.qmd
format:
  html:
    theme: 
      - flatly
      - styles-light.scss
    highlight-style: breeze
    
execute:
  freeze: auto

